#!/bin/sh

set -x

for cpu in /sys/devices/system/cpu/cpu*/cpufreq; do
	echo performance | sudo tee $cpu/scaling_governor
done

LOG="`git rev-parse HEAD`-`date +%Y%m%d-%H%M%S.log`"

echo $LOG

top -c -b -d 1 -w 512 > $LOG &
pid=$!

date
sleep 600
kill $!
wait

for cpu in /sys/devices/system/cpu/cpu*/cpufreq; do
	echo ondemand | sudo tee $cpu/scaling_governor
done
