#!/bin/sh

set -e

ADDRESS="$1"
PATTERN="$2"
PIDS="${3:-"`pgrep nacl_helper`"}"

MATCH=""

for pid in $PIDS; do
    echo "pid:$pid" 1>&2
    # FIXME: Check that address is indeed always found in last 32-bit of
    # mapping (probably no true on non-64-bit platforms)
    file="`awk '
        $1 ~ /^[0-9]*'"$ADDRESS"'-/ && $2 == "rw-s" && \
            $6 ~ /\/shm\/.com.google.Chrome/ { print $6 }
    ' "/proc/$pid/maps"`"
    echo "file:$file" 1>&2
    if [ -z "$file" ]; then
        continue
    fi
    for fd in "/proc/$pid/fd"/*; do
        link="`readlink $fd`"
        link="${link% (deleted)}"
        if [ $link == $file ]; then
           echo "FD:$fd" 1>&2
           pattern="`hexdump -n 8 -v -e '/4 "%04x"' $fd`"
           if [ "$pattern" = "$PATTERN" ]; then
              if [ -n "$MATCH" ]; then
                 echo -n "-1:ambiguous"
                 exit 1
              fi
              MATCH="$pid:$link"
           fi
        fi
    done
done

if [ -n "$MATCH" ]; then
    echo -n "$MATCH"
    exit 0
else
    echo -n "-1:no match"
    exit 1
fi