#!/bin/sh

set -e

ADDRESS="$1"
PATTERN="$2"
PIDS="${3:-"`pgrep nacl_helper`"}"

MATCH=""

#echo "$0/$1/$2/$3/" 1>&2

# Ignore last nibble
addr="${ADDRESS%?}"
lastnib="${ADDRESS#$addr}"

for pid in $PIDS; do
    echo "pid:$pid" 1>&2
    # FIXME: Check that address is indeed always found in last 32-bit of
    # mapping (probably no true on non-64-bit platforms)
    fulladdr="`awk '
        $1 ~ /^[0-9a-f]*'"$addr"'0-/ \
            && $2 ~ /rw-p/ \
            { sub(/0-.*/, "", $1); print "0x" $1 }
    ' "/proc/$pid/maps"`"

    fulladdr="$(($fulladdr$lastnib))"

    echo "fulladdr:$fulladdr" 1>&2

    if [ -z "$fulladdr" ]; then
        continue
    fi

    file="/proc/$pid/mem"
    pattern="`dd if=$file bs=1 skip=$fulladdr count=8 2>/dev/null | hexdump -v -e '/1 "%02x"' $fd`"
    echo "FD:$file ($pattern)" 1>&2
    if [ "$pattern" = "$PATTERN" ]; then
        if [ -n "$MATCH" ]; then
            echo -n "-1:ambiguous"
            exit 1
        fi
        MATCH="$pid:$file:$fulladdr"
    fi
done

if [ -n "$MATCH" ]; then
    echo -n "$MATCH"
    exit 0
else
    echo -n "-1:no match:0"
    exit 1
fi
