#!/bin/sh

set -e

VERBOSE=

ADDRESS="$1"
PATTERN="$2"
PIDS="${3:-"`pgrep nacl_helper`"}"

MATCH=""

#echo "$0/$1/$2/$3/" 1>&2

for pid in $PIDS; do
    if [ -n "$VERBOSE" ]; then echo "pid:$pid" 1>&2; fi
    # FIXME: Check that address is indeed always found in last 32-bit of
    # mapping (probably no true on non-64-bit platforms)
    file="`awk '
        $1 ~ /^[0-9a-f]*'"$ADDRESS"'-/ \
            && $2 == "rw-s" \
            && $6 ~ /\/shm\/.com.google.Chrome/ \
            { print $6 }
    ' "/proc/$pid/maps"`"
    if [ -n "$VERBOSE" ]; then echo "file:$file" 1>&2; fi
    if [ -z "$file" ]; then
        continue
    fi
    for fd in "/proc/$pid/fd"/*; do
        link="`readlink $fd`"
        link="${link% (deleted)}"
        if [ "$link" = "$file" ]; then
           pattern="`hexdump -n 8 -v -e '/1 "%02x"' $fd`"
           if [ -n "$VERBOSE" ]; then echo "FD:$fd ($pattern)" 1>&2; fi
           if [ "$pattern" = "$PATTERN" ]; then
              if [ -n "$MATCH" ]; then
                 echo -n "-1:ambiguous"
                 exit 1
              fi
              MATCH="$pid:$fd"
           fi
        fi
    done
done

if [ -n "$MATCH" ]; then
    echo -n "$MATCH"
    exit 0
else
    echo -n "-1:no match"
    exit 1
fi
