#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

for release in $SUPPORTED_RELEASES; do
    snapshot "$release" core
    crouton -u -n "$release" -t xfce
    #FIXME: Add simple test here
    host delete-chroot -y "$release"
done
