#!/bin/sh -e
# Copyright (c) 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# All supported releases should be install all targets
for release in $SUPPORTED_RELEASES; do
    for target in chrome chromium e17 gnome kde lxde touch unity xbmc xfce; do
        snapshot "$release" x11
        ret=0
        crouton -u -n "$release" -t "$target" || ret=$?
        if [ "$ret" -ne 0 ]; then
            if [ "$ret" -eq 99 ]; then
                log "Target $target failed on $release, as expected (unsupported combination)."
            else
                log "Target $target failed on $release."
                exit 1
            fi
        fi
        host delete-chroot -y "$release"
    done
done
