#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if [ -z "$release" ]; then
    echo "all"
    exit 0
fi

for target in xfce; do
    # Start with a x11 snapshot
    snapshot "$release" x11

    # Install snapshot tools
    echo 'install --minimal imagemagick pngquant xautomation' | \
        crouton -T -U -n "$release"

    ret=0
    crouton -u -n "$release" -t "$target" || ret=$?
    if [ "$ret" -ne 0 ]; then
        if [ "$ret" -eq 99 ]; then
            log "Target $target failed on $release, as expected (unsupported combination)."
        else
            log "Target $target failed on $release."
            exit "$ret"
        fi
    fi

    xte=""
    case "$target" in
    xfce)
        startcmd="startxfce4"
        # This magic sequence presses "Use default configuration"
        xte="keydown Alt_L;key Tab;key Tab;keyup Alt_L;key Left;key Left;\
keydown Return;sleep 1;keyup Return";;
    \?) echo "Unkonwn target"; exit 0;;
    esac

(
    vtlock
    host "$startcmd" -b -n "$release"
    # FIXME: Wait for $target-session or something?
    sleep 30
    host enter-chroot -n "$release" sh -exc '
        # Test croutoncycle as a bonus
        export DISPLAY="`croutoncycle display`"
        if [ "$DISPLAY" = ":0" -o "$DISPLAY" = "aura" ]; then
            echo "Invalid display ($DISPLAY)." 1>&2
            exit 1
        fi
        echo "'"$xte"'" | tr ";" "\n" | xte
        sleep 30
        # Snapshot!
        import -window root PNG:- | \
            pngquant --nofs --quality 0-20 - > ~/"screenshot-'"$target"'.png"'

    mv "$PREFIX/chroots/$release/home/test/screenshot-$target.png" \
        "$file-x11-$target.png"

    host unmount-chroot -f "$release" || true
    host unmount-chroot -f -k "$release"
)

    host delete-chroot -y "$release"
done
