#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gtk-extra'
DESCRIPTION='Installs the GNOME desktop environment. (Approx. 400MB)'
HOSTBIN='startgnome'
CHROOTBIN='startgnome gnome-session-wrapper'

if [ "$TARGETS" != 'help' -a "${DISTROAKA:-"$DISTRO"}" = 'arch' ]; then
    echo "gnome target is not supported by crouton in Arch Linux." 1>&2
    # FIXME: Arch includes Gnome 2.8, which does not have an automatic fallback
    # Even using gnome-flashback-session does not seem to help: startgnome
    # on xephyr complains about lack of hardware AND software acceleration.
    # Finally, /etc/X11/xinit/xinitrc behaviour is very different in Ubuntu vs
    # Arch (it is a fallback xinitrc in Arch, but Ubuntu's sources
    # /etc/X11/Xsession)
fi

. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install --minimal evolution-data-server gnome-control-center \
        gnome-screensaver gnome-session \
        arch=gnome-flashback-session,gnome-session-fallback \
        gnome-shell gnome-themes-standard arch=,gvfs-backends nautilus unzip

TIPS="$TIPS
You can start GNOME via the startgnome host command: sudo startgnome
"
