#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Installs the KDE desktop environment. (Approx. 800MB)'
HOSTBIN='startkde'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
# FIXME: Not fully working on Arch (no launcher to start other applications?)
install arch=,kde-standard \
    arch=kde-meta-kdeadmin, \
    arch=kde-meta-kdebase, \
    arch=kde-meta-kdegraphics, \
    arch=kde-meta-kdepim, \
    arch=kde-meta-kdeplasma-addons, \
    arch=kde-meta-kdeutils, \
    arch=kdesdk-kate, \
    -- network-manager

TIPS="$TIPS
You can start KDE via the startkde host command: sudo startkde
"
